config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Why use complex regex when you can use confirmation emails?
  VALID_EMAIL_REGEX = /.+@.+\..+/i

  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[destroy edit show update]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[destroy edit update]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article successfully created'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article successfully deleted'
    redirect_to articles_path
  end

  def edit; end

  def new
    @article = Article.new
  end

  def show; end

  def update
    if @article.update article_params
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render :edit
    end

  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    unless current_user == @article.user || current_user.admin?
      flash[:danger] = 'Access denied: You can only edit or delete your own articles'
      redirect_to root_path
    end
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Login successful'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Login failed: Username or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout successful'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit show update]
  before_action :require_same_user, only: %i[destroy edit update]
  before_action :require_admin, only: %i[destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:danger] = 'User and all their articles have been deleted'
    redirect_to users_path
  end

  def edit; end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Account details updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:danger] = 'Access denied: You are not permitted to delete users'
      redirect_to root_path
    end
  end

  def require_same_user
    unless current_user == @user || current_user.admin?
      flash[:danger] = 'Access denied: You can only edit your own details'
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="card bg-light mb-3">
    <div class="card-header article-title">
      <%= link_to article.title, article_path(article) %>
    </div>
    <div class="card-body article-body">
      <%= truncate article.description, length: 100 %>
      <div class="article-meta-details">
        <small>
          Created by <%= article.user.username if article.user %>
          <%= time_ago_in_words article.created_at %> ago,
          last updated <%= time_ago_in_words article.updated_at %> ago.
        </small>
      </div>
    </div>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
    <div class="card-body article-actions">
      <%= link_to 'Edit article', edit_article_path(article.id), class: 'btn btn-xs btn-primary' %>
      <%= link_to 'Delete this article', article_path(article.id), method: :delete,
                  data: {confirm: 'Are you sure you want to delete this article?'}, class: 'btn btn-xs btn-danger' %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <%= f.label :description %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-right col-lg-12">
      <%= f.submit class: 'btn btn-lg btn-xlarge' %>
    </div>
    <div class="text-center">
      [ <%= link_to 'Back to articles', articles_path %> ]
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 align="center">Edit article:</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">All Articles:</h1>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article:</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
  Title: <%= @article.title %>
</h2>
<% if @article.user %>
  <div align="center">
    <ul class="listing">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li>
          <small>
            <%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %>
          </small>
        </li>
    </ul>
  </div>
<% end %>
<div class="card col-xs-8 offset-xs-2">
  <div class="card-header">
    <h4 class="center">
      <strong>Description:</strong>
    </h4>
  </div>
  <div class="card-body">
    <%= simple_format @article.description %>
  </div>
  <div class="card-body article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit article', edit_article_path(@article.id), class: 'btn btn-xs btn-primary' %>
      <%= link_to 'Delete this article', article_path(@article.id), method: :delete,
                  data: { confirm: 'Are you sure you want to delete this article?'}, class: 'btn btn-xs btn-danger' %>
    <% end %>
    <%= link_to 'View all articles', articles_path, class: 'btn btn-xs btn-success' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Created by <a href="https://www.linkedin.com/in/robffoley">Rob Foley</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to 'About', about_path %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="alert">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li>
        <% if logged_in? %>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User <%= ' (Admin)' if current_user.admin? %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'View Profile', user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALPHA BLOG</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

    <div class="center">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About me:</h1>

<p><%= link_to image_tag('profile_small.png'), 'http://www.linkedin.com/in/robffoley' %></p>

<p><%= link_to 'Home', root_path %></p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <%= link_to 'Sign up now', signup_path, class: 'btn btn-lg btn-xlarge' %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="col-xs-8 offset-xs-2">
    <div class="alert alert-danger">
      <h3 class="panel-title">
        <%= pluralize(obj.errors.count, 'error') %>
        prohibited the article from being saved:
      </h3>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <%= f.label :username %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username', autofocus: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <%= f.label :email %>
    </div>
    <div class="col-sm-10">
      <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <%= f.label :password %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password' %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-right col-lg-12">
      <%= f.submit(@user.new_record? ? 'Sign up' : 'Update details', class: 'btn btn-lg btn-xlarge') %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit account details</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>
<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="card col-md-4 bg-light">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li>
          <small>
            <%= pluralize(user.articles.count, 'article') if user.articles %>
          </small>
        </li>
          <% if logged_in? and current_user.admin? %>
            <li>
              <%=
                link_to 'Delete user', user_path(user), method: :delete,
                          data: { confirm: 'Are you sure you want to delete this user and all their articles?' },
                          class: 'btn btn-xs btn-danger'
              %>
            </li>
          <% end %>
      </div>
    </ul>
  <% end %>
</div>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div align="center">
  <%= gravatar_for @user, size: 100 %>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="col-md-1 offset-md-5">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="col-md-1 offset-md-5">
  <%= will_paginate @user_articles %>
</div>